# Generated by Django 3.1.7 on 2021-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210227_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
