# Generated by Django 3.1.7 on 2021-03-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210227_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_active',
            field=models.BooleanField(choices=[(1, 'Active'), (0, 'In-Active')], default=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_adharno',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_contactno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_status',
            field=models.CharField(choices=[('T', 'Teaching Staff'), ('N', 'Non-Teaching Staff')], default='T', max_length=1),
        ),
    ]
