# Generated by Django 3.1.7 on 2021-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210302_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'In-Active')], default=False, null=True),
        ),
    ]
